- platform: workday
  country: GB
  name: workday_today
# - platform: workday
#   country: GB
#   name: workday_tomorrow
#   days_offset: 1
#   add_holidays:
#     - "2021-10-12"
#     - "2021-10-13"
#     - "2021-10-14"
#     - "2021-10-15"

- platform: template
  sensors:
    office_occupation:
      value_template: >
        {{
            is_state('light.office_lamp', 'on')
            or is_state('binary_sensor.in_meeting', 'on')
            or is_state('binary_sensor.in_meeting', 'off')
        }}
    dark_outside:
      value_template: >
        {{
            state_attr("sun.sun", "elevation") < 0
            or states(sensor.openweathermap_cloud_coverage) | int > 95
        }}
