- platform: workday
  country: GB
  # name: workday
  workdays: [mon, fri, sat]
  excludes: [tue, wed, thu, sun]
  # add_holidays:
  #   - "2021-10-12"
  #   - "2021-10-13"
  #   - "2021-10-14"
  #   - "2021-10-15"

- platform: template
  sensors:
    office_occupation:
      value_template: >
        {{
            is_state('light.office_lamp', 'on')
            or is_state('device_tracker.dell_dock_eth', 'home')
        }}
    dark_outside:
      value_template: >
        {{
            state_attr("sun.sun", "elevation") < 0
        }}
    dark_upstairs:
      value_template: >
        {{
            int(min(
              states('sensor.illumination_upstairs'),
              states('sensor.bathroom_illumination'),
              states('sensor.toilet_illumination'),            
            )) <= 10
        }}
