- platform: workday
  country: GB
  name: workday_today
    add_holidays:
      - "2021-10-12"
      - "2021-10-13"
      - "2021-10-14"
      - "2021-10-15"
- platform: workday
  country: GB
  name: workday_tomorrow
  days_offset: 1
    add_holidays:
      - "2021-10-12"
      - "2021-10-13"
      - "2021-10-14"
      - "2021-10-15"
