# - platform: xiaomi_miio
#   host: !secret toilet_light_ip
#   name: Toilet Light
#   token: !secret toilet_light_token
#   model: philips.light.bulb
# - platform: xiaomi_miio
#   host: !secret bathroom_light_ip
#   name: Bathroom Light
#   token: !secret bathroom_light_token
#   model: philips.light.bulb
- platform: group
  name: Bedroom Light
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
- platform: group
  name: Kid's Room Light
  entities:
    - light.kids_room_light
    - light.kids_room_lamp
- platform: group
  name: Loft Light
  entities:
    - light.loft_light_1
    - light.loft_light_2
    - light.loft_light_3
