- platform: template
  sensors:
    sunset_time:
      value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
      friendly_name: "Next setting"
    sunrise_time:
      value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
      friendly_name: "Next rising"
    washer_status:
      friendly_name: "Washing Machine"
      value_template: >
        {% set washer_state = states('sensor.washing_machine_washer_job_state') %}
        {% set off_states = ["none", "finish"] %}
        {%- if washer_state in off_states -%}Off
        {%- elif washer_state == "weightSensing" -%}Weighing
        {%- elif washer_state == "delayWash" -%}Delay
        {%- elif washer_state == "rinse" -%}Rinsing
        {%- elif washer_state == "spin" -%}Spinning
        {%- elif washer_state == "wash" -%}Washing
        {%- else -%}{{ washer_state }}
        {%- endif %}
    washer_eta:
      friendly_name: "Completion Time Estimate"
      value_template: >
        {% set washer_state = states('sensor.washer_status') %}
        {%- if washer_state == "Off" -%}None
        {%- else -%}{{ as_timestamp(strptime(states('sensor.washing_machine_washer_completion_time'), "")) | timestamp_custom("%H:%M") }}
        {%- endif %}
    doorbell_last_triggered:
      friendly_name: "Doorbell pressed"
      value_template: >
        {% set date = strptime(states.automation.doorbell.attributes.last_triggered, '') %}
        {%- if date.date() != now().date() -%}Not today
        {%- else -%}{{ as_timestamp(date) | timestamp_custom('%H:%M') }}
        {%- endif %}
    office_aqi:
      friendly_name: "Office Air Quality"
      value_template: '{{ states.fan.office_purifier.attributes.aqi }}'
      unit_of_measurement: 'PM'
