- alias: Heating off every night
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: script.heating_night

- alias: Heating on every morning
  trigger:
    platform: time
    at: '6:30:00'
  action:
    - delay: "{{ '00:00:00' if is_state('binary_sensor.workday_sensor', 'on') else '02:00:00' }}"
    - service: script.heating_init

- alias: Back home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'not_home'
      to: 'home'
  action:
    service: script.turn_on
    data:
      entity_id: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    service: script.turn_on
    data:
      entity_id: script.leave_home

- alias: Notify zone changes
  trigger:
    platform: state
    entity_id: person.janca, person.lubos
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.state is not none and
          trigger.from_state.state is not none and
          trigger.to_state.state != trigger.from_state.state }}
    - condition: template
      value_template: >
        {% set zones = states.zone | map(attribute='name')|list %}
        {{trigger.to_state.state in ['home','not_home'] or
          trigger.from_state.state in ['home','not_home'] or
          trigger.to_state.state in zones or 
          trigger.from_state.state in zones}}
  action:     
    - service_template: >
        script.notify_presence
      data_template:
        trigger: Presence tracking
        entityid: '{{trigger.entity_id}}'
        tostate: '{{trigger.to_state.state}}'
        fromstate: '{{trigger.from_state.state}}'

- alias: Gateway light on
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 450
  action:
    - service: light.turn_on
      data:
        entity_id: light.xiaomi_gateway_light
        color_name: azure

- alias: Gateway light off
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    above: 600
  action:
    service: light.turn_off
    entity_id: light.xiaomi_gateway_light

- alias: Play radio
  trigger:
    - platform: state
      entity_id: input_select.play_radio
      from: 'Select radio'
  action:
    - service: script.play_radio
    - service: input_select.select_option
      data:
        entity_id: input_select.play_radio
        option: 'Select radio'
