- alias: Bathroom light on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c8ca
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom_light

- alias: Bathroom light off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c8ca
    to: 'off'
    for: '00:03:00'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light

- alias: Cupboard light on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001656352
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.cupboard_light

- alias: Cupboard light off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001656352
    to: 'off'
    for: '00:00:30'
  action:
    service: light.turn_off
    entity_id: light.cupboard_light

- alias: Gateway light on
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce00889d79
        color_name: azure

- alias: Gateway light off
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  action:
    service: light.turn_off
    entity_id: light.gateway_light_34ce00889d79

- alias: Heating and purifiers off every night
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: fan.turn_off
      data:
        entity_id: group.purifiers
    - service: climate.set_preset_mode
      data:
        entity_id: climate.lounge_temperature
        preset_mode: away

- alias: Heating on every morning
  trigger:
    platform: time
    at: '5:30:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.lounge_temperature
        temperature: 21
    - service: climate.set_preset_mode
      data:
        entity_id: climate.lounge_temperature
        preset_mode: none

- alias: Kodi Library Updates
  trigger:
    platform: time
    at: '02:00:00'
  action:
    service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi
      method: VideoLibrary.Scan

- alias: Kitchen lights on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21126
      click_type: single
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_light
    - service: light.turn_on
      data:
        entity_id: light.kitchen_lightstrip


- alias: Kitchen lights off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21126
      click_type: hold
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen_light
    - service: light.turn_off
      data:
        entity_id: light.kitchen_lightstrip

- alias: Vacuum kitchen
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21126
      click_type: double
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[25700,26100,28100,27800,1]]

- alias: Vacuum the bathroom
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00015639f9
      click_type: double
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[21420,27680,22370,29880,1]]

- alias: Hall light on when door opens
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a647fc
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_light

- alias: Hall light off after door closes
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a647fc
    to: 'off'
    for: '00:01:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.hall_light

- alias: Hall light toggle
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00015639f9
      click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.hall_light

- alias: Turn on speaker when Kodi is playing
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  action:
    service: media_player.turn_on
    data:
      entity_id: "media_player.tv_speaker"

- alias: Turn on speaker when Chromecast is playing
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
  action:
    service: media_player.turn_on
    data:
      entity_id: "media_player.tv_speaker"

- alias: Purifiers off when cleanup done
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    from: cleaning
  action:
    service: fan.turn_off
    data:
      entity_id: group.all_fans

- alias: Notify when door opens
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a647fc
    to: 'on'
  action:
    service: notify.notify
    data:
      title: Home Assistant
      message: Door just opened

- alias: Back home
  trigger:
    - platform: state
      entity_id: person.lubos
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: person.janca
      from: 'not_home'
      to: 'home'
  action:
    service: script.turn_on
    data:
      entity_id: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
  action:
    service: script.turn_on
    data:
      entity_id: script.leave_home

- alias: Notify zone changes
  trigger:
    platform: state
    entity_id: person.janca, person.lubos
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.state is not none and
          trigger.from_state.state is not none and
          trigger.to_state.state != trigger.from_state.state }}
    - condition: template
      value_template: >
        {% set zones = states.zone | map(attribute='name')|list %}
        {{trigger.to_state.state in ['home','not_home'] or
          trigger.from_state.state in ['home','not_home'] or
          trigger.to_state.state in zones or 
          trigger.from_state.state in zones}}
  action:     
    - service_template: >
        script.notify_presence
      data_template:
        trigger: Presence tracking
        entityid: '{{trigger.entity_id}}'
        tostate: '{{trigger.to_state.state}}'
        fromstate: '{{trigger.from_state.state}}'
