title: ''
views:
  - badges:
      - entity: person.lubos
      - entity: person.janca
      - entity: switch.heating
      - entity: sensor.sunrise_time
      - entity: sensor.sunset_time
    cards:
      - entity: climate.lounge_temperature
        type: thermostat
      - entity: media_player.tv_speaker
        type: media-control
      - entity: media_player.kodi
        type: media-control
      - entity: media_player.living_room_tv
        type: media-control
      - entities:
          - entity: sensor.temperature_158d0001217046
          - entity: sensor.lounge_temperature
          - entity: sensor.bedroom_temperature
        show_header_toggle: false
        title: Temperature
        type: entities
      - entities:
          - entity: vacuum.xiaomi_vacuum_cleaner
          - entity: input_select.vacuum_room
        show_header_toggle: false
        theme: Backend-selected
        title: Vacuum
        type: entities
      - entity: weather.home
        type: weather-forecast
      - entities:
          - fan.lounge_purifier
          - fan.bedroom_purifier
        show_header_toggle: true
        title: Air Purifiers
        type: entities
      # - type: picture-entity
      #   entity: camera.bedroom_camera
      # - type: picture-entity
      #   entity: camera.kitchen_camera
      - detail: 2
        entity: sensor.speedtest_download
        graph: line
        hours_to_show: 168
        theme: default
        type: sensor
    icon: ''
    path: default_view
    title: Home
  - badges:
      - entity: group.everyone
      - entity: binary_sensor.door_window_sensor_158d0001a647fc
      - entity: binary_sensor.motion_sensor_158d000121c8ca
      - entity: binary_sensor.motion_sensor_158d0001656352
      - entity: binary_sensor.switch_158d00015639f9
      - entity: binary_sensor.switch_158d0001a21126
      - entity: switch.plug_158d00015d1e94
      - entity: switch.heating
      - entity: sensor.illumination_34ce00889d79
      - entity: sensor.cert_expiry_jerabin_myqnapcloud_com
    cards:
      - entities:
          - light.kitchen_light
          - light.kitchen_lightstrip
        show_header_toggle: true
        title: Kitchen lights
        type: entities
      - entities:
          - light.argos_lamp
          - light.living_room_light
          - light.ikea_lamp
          - light.desk_lamp
        show_header_toggle: true
        title: Living room lights
        type: entities
      - entities:
          - light.bedroom_light
          - light.cupboard_light
          - light.bathroom_light
          - light.gateway_light_34ce00889d79
          - light.hall_light
        show_header_toggle: true
        title: Other lights
        type: entities
      - detail: 2
        entity: sensor.speedtest_download
        graph: line
        hours_to_show: 168
        theme: default
        type: sensor
      - detail: 10
        entity: sensor.speedtest_upload
        graph: line
        hours_to_show: 168
        type: sensor
      - entity: sensor.speedtest_ping
        max: 100
        min: 0
        theme: default
        type: gauge
      - entities:
          - entity: fan.lounge_purifier
          - entity: fan.bedroom_purifier
        show_icon: true
        show_name: true
        show_state: true
        theme: Backend-selected
        title: Purifiers
        type: glance
    icon: ''
    path: devices
    title: Devices
  - badges: []
    cards:
      - entities:
          - entity: sensor.lubos_at_work_today
          - entity: sensor.lubos_at_work_this_week
          - entity: sensor.janca_at_work_today
          - entity: sensor.janca_at_work_this_week
        show_header_toggle: false
        type: entities
      - entities:
          - entity: sensor.heating_on_today
          - entity: sensor.heating_on_yesterday
          - entity: sensor.heating_on_past_month
        show_header_toggle: false
        type: entities
      - entities:
          - entity: person.lubos
        hours_to_show: 24
        type: map
      - entities:
          - entity: person.janca
        hours_to_show: 24
        type: map
      - entity: media_player.lounge
        type: media-control
      - entity: media_player.home_group
        type: media-control
      - entity: media_player.tv_speaker
        type: media-control
      - entity: media_player.kodi
        type: media-control
      - entity: media_player.living_room_tv
        type: media-control
      - entity: media_player.bedroom_speaker
        type: media-control
    icon: ''
    path: info
    title: Info
