- alias: Back home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'not_home'
      to: 'home'
  action:
    - service: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.leave_home

- alias: Play radio downstairs
  trigger:
    - platform: state
      entity_id: input_select.play_radio_downstairs
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio_downstairs
        state: 'Select radio'
  action:
    - service: script.play_radio_downstairs
    - delay: '00:00:05'
    - service: input_select.select_option
      data:
        entity_id: input_select.play_radio_downstairs
        option: 'Select radio'

- alias: Play radio kid's room
  trigger:
    - platform: state
      entity_id: input_select.play_radio_kids_room
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio_kids_room
        state: 'Select radio'
  action:
    - service: script.play_radio_kids_room
    - delay: '00:00:05'
    - service: input_select.select_option
      data:
        entity_id: input_select.play_radio_downstairs
        option: 'Select radio'

- alias: Doorbell
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell
  action:
    - service: script.doorbell

- alias: Cube - Start work
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: tap_twice
  action:
    - service: script.start_work

- alias: Cube - Finish work
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: shake_air
  action:
    - service: script.finish_work

- alias: Bedside - Lubos Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.lubos_bedside_button
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.lubos_bedside_button', 'last_action') }}

- alias: Bedside - Jana Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.jana_bedside_button
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.jana_bedside_button', 'last_action') }}

- alias: Home - Select home mode in the morning
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    - condition: state
      entity_id: group.everyone
      state: home
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.hassio_mode
        option: home

- alias: Stop music when xbox starts playing
  trigger:
    - platform: state
      entity_id: media_player.xboxone
      from: 'on'
      to: 'playing'
  action:
    - service: media_player.turn_off
      entity_id:
        - media_player.downstairs_speakers

- alias: Reload automations
  trigger:
    - platform: webhook
      webhook_id: automations
  action:
    - service: automation.reload

- alias: Reload integrations
  trigger:
    - platform: webhook
      webhook_id: integrations
  action:
    - service: homeassistant.restart

- alias: Reload scripts
  trigger:
    - platform: webhook
      webhook_id: scripts
  action:
    - service: script.reload
