- alias: Back home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'not_home'
      to: 'home'
  action:
    - service: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.leave_home

- alias: Play radio
  trigger:
    - platform: state
      entity_id: input_select.play_radio
      from: 'Select radio'
  action:
    - service: script.play_radio
    - service: input_select.select_option
      data:
        entity_id: input_select.play_radio
        option: 'Select radio'

- alias: Doorbell
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21126
      click_type: single
  action:
    - service: script.doorbell

- alias: Cube automations
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: tap_twice
  action:
    - service: script.start_work

- alias: Bedside automations - Toggle light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.button_bedside_lubos
      click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.bedroom_lamp

- alias: Bedside automations - Bedtime script
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.button_bedside_lubos
      click_type: double
  action:
    - service: script.bedtime

- alias: Bedside automations - Morning script
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.button_bedside_lubos
      click_type: hold
  action:
    - service: script.morning
