- alias: Back home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'not_home'
      to: 'home'
  action:
    - service: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.leave_home

- alias: Play radio
  trigger:
    - platform: state
      entity_id: input_select.play_radio
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio
        state: 'Select radio'
  action:
    - service: script.play_radio
    - service: input_select.select_option
      data:
        entity_id: input_select.play_radio
        option: 'Select radio'

- alias: Doorbell
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21126
  action:
    - service: script.doorbell

- alias: Cube automations
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: tap_twice
  action:
    - service: script.start_work

- alias: Bedside - Lubos Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.button_bedside_lubos
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.button_bedside_lubos', 'last_action') }}

- alias: Bedside - Jana Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.button_bedside_jana
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.button_bedside_jana', 'last_action') }}
