- alias: Back home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'not_home'
      to: 'home'
  action:
    - service: script.back_home

- alias: Leave home
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.leave_home

- alias: Play radio downstairs
  trigger:
    - platform: state
      entity_id: input_select.play_radio_downstairs
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio_downstairs
        state: 'Select radio'
  action:
    - service: script.play_radio
      data_template:
        media_player: media_player.downstairs_speakers
        input_select: input_select.play_radio_downstairs

- alias: Play radio kid's room
  trigger:
    - platform: state
      entity_id: input_select.play_radio_kids_room
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio_kids_room
        state: 'Select radio'
  action:
    - service: script.play_radio
      data_template:
        media_player: media_player.kids_room_speaker
        input_select: input_select.play_radio_kids_room

- alias: Play radio loft
  trigger:
    - platform: state
      entity_id: input_select.play_radio_loft
      from: 'Select radio'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_select.play_radio_loft
        state: 'Select radio'
  action:
    - service: script.play_radio
      data_template:
        media_player: media_player.loft_speaker
        input_select: input_select.play_radio_loft

- alias: White noises player kid's room
  trigger:
    - platform: state
      entity_id: input_select.white_noises_player_kids_room
      from: 'Select noise'
  action:
    - service: script.play_white_noises
      data_template:
        white_noise_media_path: !secret white_noise_media_path
        media_player: media_player.kids_room_speaker
        input_select: input_select.white_noises_player_kids_room

- alias: White noises player bedroom
  trigger:
    - platform: state
      entity_id: input_select.white_noises_player_bedroom
      from: 'Select noise'
  action:
    - service: script.play_white_noises
      data_template:
        white_noise_media_path: !secret white_noise_media_path
        media_player: media_player.bedroom_speaker
        input_select: input_select.white_noises_player_bedroom

- alias: Doorbell
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell
  action:
    - service: script.doorbell

- alias: Cube - Start work
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: tap_twice
  action:
    - service: script.start_work

- alias: Cube - Finish work
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: shake_air
  action:
    - service: script.finish_work

- alias: Bedside - Lubos Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.lubos_bedside_button
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.lubos_bedside_button', 'last_action') }}

- alias: Bedside - Jana Button
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.jana_bedside_button
      click_type: double
  action:
    - service: script.bedside_actions
      data_template:
        action: >
          {{ state_attr('binary_sensor.jana_bedside_button', 'last_action') }}

- alias: Kids Room - Bedtime
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.kids_room_button
      click_type: double
  action:
    - service: script.kids_bedtime

- alias: Home - Disable night lights every morning
  trigger:
    platform: time
    at: "06:00:00"
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.night_mode
        - input_boolean.kids_night_light

- alias: Stop music when xbox starts playing
  trigger:
    - platform: state
      entity_id: media_player.xboxone
      from: 'on'
      to: 'playing'
  action:
    - service: media_player.turn_off
      entity_id:
        - media_player.downstairs_speakers

- alias: Reload automations
  trigger:
    - platform: webhook
      webhook_id: automations
  action:
    - service: automation.reload

- alias: Reload integrations
  trigger:
    - platform: webhook
      webhook_id: integrations
  action:
    - service: homeassistant.restart

- alias: Reload scripts
  trigger:
    - platform: webhook
      webhook_id: scripts
  action:
    - service: script.reload
