- alias: Heating off every night
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: script.heating_night

- alias: Heating on every morning
  trigger:
    platform: time
    at: '6:30:00'
  action:
    - delay: "{{ '00:00:00' if is_state('binary_sensor.workday_sensor', 'on') else '01:00:00' }}"
    - service: script.heating_morning

- alias: Heating off when window open
  trigger:
    platform: state
    entity_id:
      - sensor.living_room_open_window
      - sensor.bedroom_open_window
      - sensor.kitchen_open_window
      - sensor.study_open_window
      - sensor.loft_open_window
    from: 'False'
    to: 'True'
  action:
    - service: script.notify_heating_off
      data_template:
        entityid: '{{trigger.entity_id}}'

- alias: Evening heating before Jana gets back home
  trigger:
    - platform: zone
      entity_id: person.janca
      zone: zone.extended_home
      event: enter
  condition:
    - condition: state
      entity_id: person.lubos
      state: 'home'
  action:
    - service: script.set_thermostat
      data:
        entity_id: climate.living_room
        temperature: 21
    - service: script.set_thermostat
      data:
        entity_id: climate.bedroom
        temperature: 21

