- alias: Heating - Everyone Leaves
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.heating_away

- alias: Heating - Someone Arrives Home
  trigger:
    platform: state
    entity_id: person.jana, person.lubos
    to: 'home'
  action:
    - service: script.heating_back

- alias: Heating - Close to home
  trigger:
    - platform: zone
      entity_id: person.jana, person.lubos
      zone: zone.extended_home
      event: enter
  action:
    - service: script.heating_close

- alias: Heating - Restart Tado bridge when service goes down
  trigger:
    platform: state
    entity_id:
      - binary_sensor.living_room_link
      - binary_sensor.bedroom_link
      - binary_sensor.kitchen_link
      - binary_sensor.office_link
      - binary_sensor.loft_link
    from: 'on'
    to: 'off'
  action:
    - service: script.restart_tado
