- alias: Heating - Night
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: script.heating_night

- alias: Heating - Morning
  trigger:
    platform: time
    at: '6:30:00'
  action:
    - delay: "{{ '00:00:00' if is_state('binary_sensor.workday_sensor', 'on') else '01:00:00' }}"
    - service: script.heating_morning

- alias: Heating - Temperature drop
  trigger:
    platform: state
    entity_id:
      - sensor.living_room_open_window
      - sensor.bedroom_open_window
      - sensor.kitchen_open_window
      - sensor.study_open_window
      - sensor.loft_open_window
    from: 'False'
    to: 'True'
  action:
    - service: script.notify_heating_off
      data_template:
        entityid: '{{trigger.entity_id}}'

- alias: Heating - Close to home
  trigger:
    - platform: zone
      entity_id: person.janca, person.lubos
      zone: zone.extended_home
      event: enter
  condition:
    - condition: state
      entity_id: group.everyone
      state: 'home'
  action:
    - service: script.set_thermostat
      data:
        entity_id: climate.living_room
        temperature: 21
    - service: script.set_thermostat
      data:
        entity_id: climate.bedroom
        temperature: 21

- alias: Heating - Restart Tado bridge when service goes down
  trigger:
    platform: state
    entity_id:
      - sensor.living_room_link
      - sensor.bedroom_link
      - sensor.kitchen_link
      - sensor.study_link
      - sensor.loft_link
    from: 'ONLINE'
    to: 'OFFLINE'
  action:
    - service: script.restart_tado
