- alias: Heating - Night
  trigger:
    platform: time
    at: input_datetime.heating_off
  action:
    - service: script.heating_night

- alias: Heating - Everyone Leaves
  trigger:
    - platform: state
      entity_id: group.everyone
      from: 'home'
      to: 'not_home'
  action:
    - service: script.heating_away

- alias: Heating - Someone Arrives Home
  trigger:
    platform: state
    entity_id: person.jana, person.lubos
    to: 'home'
  action:
    - service: script.heating_back

- alias: Heating - Early morning
  trigger:
    platform: time
    at: input_datetime.heating_on
  action:
    - service: script.heating_early_morning

- alias: Heating - Morning
  trigger:
    platform: time
    at: input_datetime.morning
  action:
    - service: script.heating_morning

- alias: Heating - Temperature drop
  trigger:
    platform: state
    entity_id:
      - sensor.living_room_open_window
      - sensor.bedroom_open_window
      - sensor.kitchen_open_window
      - sensor.office_open_window
      - sensor.loft_open_window
    from: 'False'
    to: 'True'
  action:
    - service: script.notify_heating_off
      data_template:
        entityid: '{{trigger.entity_id}}'

- alias: Heating - Close to home
  trigger:
    - platform: zone
      entity_id: person.jana, person.lubos
      zone: zone.extended_home
      event: enter
  action:
    - service: script.heating_close

- alias: Heating - Restart Tado bridge when service goes down
  trigger:
    platform: state
    entity_id:
      - binary_sensor.living_room_link
      - binary_sensor.bedroom_link
      - binary_sensor.kitchen_link
      - binary_sensor.office_link
      - binary_sensor.loft_link
    from: 'on'
    to: 'off'
  action:
    - service: script.restart_tado

- alias: Heating - Refresh Early Morning Timer
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
    condition: state
    entity_id: input_boolean.preheating
    state: 'on'
  action:
    - service: script.refresh_early_morning_timer
