- alias: Light - Gateway light on
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 450
  action:
    - service: light.turn_on
      data:
        entity_id: light.xiaomi_gateway_light
        color_name: azure

- alias: Light - Gateway light off
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    above: 600
  action:
    service: light.turn_off
    entity_id: light.xiaomi_gateway_light

- alias: Light - Motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.hallway_light

- alias: Light - No motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: switch.turn_off
    entity_id: switch.hallway_light

- alias: Light - Motion in toilet
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.toilet_light

- alias: Light - No motion in toilet
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: light.turn_off
    entity_id: light.toilet_light

- alias: Light - Kitchen and Bedroom on upon Arrival
  trigger:
    platform: state
    entity_id: person.lubos, person.janca
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_light
    - service: light.turn_on
      entity_id: light.bedroom_lamp
