- alias: Gateway light on
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 450
  action:
    - service: light.turn_on
      data:
        entity_id: light.xiaomi_gateway_light
        color_name: azure

- alias: Gateway light off
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    above: 600
  action:
    service: light.turn_off
    entity_id: light.xiaomi_gateway_light

- alias: Light - Motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.hallway_light

- alias: Light - No motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: switch.turn_off
    entity_id: switch.hallway_light

- alias: Ambilight off when lights turn on
  trigger:
    - platform: state
      entity_id: light.living_room_light
      from: 'off'
      to: 'on'
  action:
    - service: script.ambilight_off

