- alias: Light - Gateway light on
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 450
  action:
    - service: script.home_light
      data:
        entity_id: light.xiaomi_gateway_light

- alias: Light - Gateway light off
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    above: 600
  action:
    service: light.turn_off
    entity_id: light.xiaomi_gateway_light

- alias: Light - Motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.hallway_light

- alias: Light - No motion in hallway
  trigger:
    platform: state
    entity_id: group.hallway_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: switch.turn_off
    entity_id: switch.hallway_light

- alias: Light - Motion in toilet
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.toilet_illumination
      below: 10
  action:
    service_template: >
        {% if is_state("input_boolean.night_mode", "on") %} script.night_light
        {% else %} script.bright_light
        {% endif %}
    data:
      entity_id: light.toilet_light

- alias: Light - No motion in toilet
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: light.turn_off
    entity_id: light.toilet_light

- alias: Light - Motion in bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.bathroom_illumination
      below: 5
  action:
    service_template: >
        {% if is_state("input_boolean.night_mode", "on") %} script.night_light
        {% else %} script.bright_light
        {% endif %}
    data:
      entity_id: light.bathroom_light
      
- alias: Light - No motion in bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for: '00:01:00'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light

- alias: Light - Late Arrival
  trigger:
    platform: state
    entity_id: person.lubos, person.jana
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_light
    - service: script.home_light
      data:
        entity_id: light.bedroom_light
    - service: script.home_light
      data:
        entity_id: light.dining_room_light
    - service: script.home_light
      data:
        entity_id: light.upstairs_hall_light

- alias: Light - Toggle Office using Cube
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube
      action_type: flip90
  action:
    - service: light.toggle
      entity_id: light.office_light

- alias: Light - Toggle Kid's Room Lights
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.kids_room_button
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.kid_s_room_light

- alias: Light - Mirror Kitchen Light Status
  trigger:
    platform: state
    entity_id: switch.kitchen_light
  action:
    - service_template: >
        {% if is_state("switch.kitchen_light", "on") %}light.turn_on
        {% else %}light.turn_off
        {% endif %}
      entity_id: light.kitchen_lightstrip

- alias: Holiday - Simulate lights
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_light
    - delay:
        hours: 0
        minutes: 3
        seconds: 45
        milliseconds: 0
    - service: light.turn_on
      entity_id: light.bedroom_light
    - delay:
        hours: 1
        minutes: 30
        seconds: 0
        milliseconds: 0
    - service: switch.turn_off
      entity_id: switch.kitchen_light
    - delay:
        hours: 0
        minutes: 45
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
      entity_id: light.bedroom_light
