- alias: Gateway light on
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 450
  action:
    - service: light.turn_on
      data:
        entity_id: light.xiaomi_gateway_light
        color_name: azure

- alias: Gateway light off
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    above: 600
  action:
    service: light.turn_off
    entity_id: light.xiaomi_gateway_light

- alias: Ambilight off when TV starts in daylight
  trigger:
    - platform: state
      entity_id: light.living_room_light
      from: 'unavailable'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service: script.ambilight_off

- alias: Ambilight on when lights turn off
  trigger:
    - platform: state
      entity_id: light.living_room_light
      from: 'on'
      to: 'off'
  condition:
    condition: numeric_state
    entity_id: sensor.xiaomi_gateway_illuminance
    below: 600
  action:
    - service: script.ambilight_on

- alias: Ambilight off when lights turn on
  trigger:
    - platform: state
      entity_id: light.living_room_light
      from: 'off'
      to: 'on'
  action:
    - service: script.ambilight_off

